export const DEFAULT_VALUE_ZERO = 0;
export const DEFAULT_MIN_PASSWORD_LENGTH = 8;
export const DEFAULT_ACCESS_TOKEN_EXPIRY = 15 * 60 * 1000; // 15 minutes
export const DEFAULT_REFRESH_TOKEN_EXPIRY = 7 * 24 * 60 * 60 * 1000; // 7 days

export enum APP_LANGUAGES {
  EN = 'en',
  HI = 'hi',
}

export enum API_RESPONSE_CODES {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_LOGGED_IN_SUCCESSFULLY = 'USER_LOGGED_IN_SUCCESSFULLY',
  USER_LOGGED_OUT_SUCCESSFULLY = 'USER_LOGGED_OUT_SUCCESSFULLY',
  USER_REGISTERED_SUCCESSFULLY = 'USER_REGISTERED_SUCCESSFULLY',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}